@startuml main
(*)-->[with name & password]"login"

if "user exist" then
--> [token]"edit /show user info/reset pw"
-right-> (*)

else
-> [token]"logout"
-right-> (*)

else
-> [token]"add task"
-> [token]"update/delete task"
-->(*)
@enduml