@startuml transaction
class TransactionParser
interface Transaction {
    + execute()
}
TransactionParser -> Transaction: <<create>>
@enduml

@startuml AddEmployeeTransaction
title Add Employee
interface Transaction
class AddEmployeeTransaction {
    - empid
    - itsAddress
    - itsName
}
class Employee {
    + setSchedule()
    +setClassification()
    +setMethod()
}
class PayrollDatabase
class HoldMethod
class AddHourlyEmployee {
    - hourlyRate
}
class AddSalariedEmployee {
    - salary
}
class AddCommissionedEmployee {
    - salary
    - commissionRate
}
class WeeklySchedule
class BiweeklySchedule
class MonthlySchedule
class HourlyClassification
class SalariedClassification
class CommissionedClassification

Transaction <|-- AddEmployeeTransaction
AddEmployeeTransaction -> Employee: <<creates>>
AddEmployeeTransaction -> PayrollDatabase: <<global>>
AddEmployeeTransaction -> HoldMethod: <<creates>>
AddEmployeeTransaction <|-- AddHourlyEmployee
AddEmployeeTransaction <|-- AddSalariedEmployee
AddEmployeeTransaction <|-- AddCommissionedEmployee
AddHourlyEmployee --> HourlyClassification: <<creates>>
AddHourlyEmployee --> WeeklySchedule: <<creates>>
AddSalariedEmployee --> SalariedClassification: <<creates>>
AddSalariedEmployee --> MonthlySchedule: <<creates>>
AddCommissionedEmployee --> CommissionedClassification: <<creates>>
AddCommissionedEmployee --> BiweeklySchedule: <<creates>>
@enduml

@startuml AddEmployeeProgress
title Add Employee Progress
actor user
user -> AddEmployeeTransaction: Execute
activate AddEmployeeTransaction
AddEmployeeTransaction -> Employee: name, address
AddEmployeeTransaction -> AddEmployeeTransaction: GetClassiflication
activate AddEmployeeTransaction
deactivate AddEmployeeTransaction
AddEmployeeTransaction -> Employee: SetClassification
activate Employee
deactivate Employee
AddEmployeeTransaction -> AddEmployeeTransaction: GetSchedule
activate AddEmployeeTransaction
deactivate AddEmployeeTransaction
AddEmployeeTransaction -> Employee: SetSchedule
activate Employee
deactivate Employee
AddEmployeeTransaction -> HoldMethod
AddEmployeeTransaction -> Employee: SetMethod
AddEmployeeTransaction -> PayrollDatabase: AddEmployee(employee)
deactivate AddEmployeeTransaction
activate PayrollDatabase
deactivate PayrollDatabase
@enduml

@startuml DeleteEmployeeTransaction
title Delete Employee
interface Transaction
class DeleteEmployeeTransaction {
    - empid
}
class PayrollDatabase
Transaction <|-- DeleteEmployeeTransaction
DeleteEmployeeTransaction -> PayrollDatabase

@enduml

@startuml DeleteEmployeeProgress
actor user
participant DeleteEmployeeTransaction
participant PayrollDatabase
user -> DeleteEmployeeTransaction: Execute
activate DeleteEmployeeTransaction
DeleteEmployeeTransaction -> PayrollDatabase: DeleteEmployee(empid)
activate PayrollDatabase
deactivate PayrollDatabase
deactivate DeleteEmployeeTransaction
@enduml

@startuml TimeCardTransaction
interface Transaction
class TimeCardTransaction {
    - date
    - hours
    - empId
}
class PayrollDatabase
class TimeCard {
    - date
    - hours
}
class Employee
class HourlyClassification
Transaction <|-- TimeCardTransaction
TimeCardTransaction -> PayrollDatabase
TimeCardTransaction --> TimeCard
TimeCardTransaction --> Employee
TimeCardTransaction --> HourlyClassification
Employee --> PaymentClassification
HourlyClassification --|> PaymentClassification
@enduml

@startuml TimeCardProgress
actor user
participant TimeCardTransaction
participant PayrollDatabase
participant Employee
participant TimeCard
participant HourlyClassification
user -> TimeCardTransaction: Execute
activate TimeCardTransaction
TimeCardTransaction -> PayrollDatabase: GetEmployee(empId): Employee
activate PayrollDatabase
deactivate PayrollDatabase
TimeCardTransaction -> Employee: GetPaymentClassification(): PaymentClassification
activate Employee
Employee -> HourlyClassification: <<create>>
deactivate Employee
TimeCardTransaction -> TimeCard: date, hours
TimeCardTransaction -> HourlyClassification: AddTimeCard(timeCard)
@enduml